Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Phone> favPhones { get; set; }
    }
}

Shop/ViewModels/PhonesListViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;

namespace Shop.ViewModels
{
    public class PhonesListViewModel
    {
        public IEnumerable<Phone> allPhones { get; set; }
        public string currCategory { get; set; }
    }
}

Shop/ViewModels/ShopPhoneViewModel.cs
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class ShopPhoneViewModel
    {
        public ShopPhones shopPhones { get; set; }
    }
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllPhones _phoneRep;

        public HomeController(IAllPhones phoneRep)
        {
            _phoneRep = phoneRep;
        }

        public ViewResult Index()
        {
            var homePhones = new HomeViewModel
            {
                favPhones = _phoneRep.getFavPhones
            };
            return View(homePhones);
        }
    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Shop.Data.Interfaces;
using Shop.Data.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopPhones shopPhones;

        public OrderController(IAllOrders allOrders, ShopPhones shopPhones)
        {
            this.allOrders = allOrders;
            this.shopPhones = shopPhones;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopPhones.listShopItems = shopPhones.getShopItems();

            if(shopPhones.listShopItems.Count == 0)
            {
                ModelState.AddModelError("","У Вас должны быть товары!");
            }

            if(ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        } 

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан!";
            return View();
        }
    }
}

Shop/Controllers/PhonesController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Shop.Controllers
{
    public class PhonesController : Controller
    {
        private readonly IAllPhones _allPhones;
        private readonly IPhonesCategory _phonesCategory;

        public PhonesController(IAllPhones iAllPhones, IPhonesCategory iPhonesCategory)
        {   
            _allPhones = iAllPhones; 
            _phonesCategory = iPhonesCategory;
        }

        [Route("Phones/List")]
        [Route("Phones/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Phone> phones = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                phones = _allPhones.Phones.OrderBy(i => i.id);
            } else
            {
                if (string.Equals("apple", category, StringComparison.OrdinalIgnoreCase))
                {
                    phones = _allPhones.Phones.Where(i => i.Category.categoryName.Equals("IOS")).OrderBy(i => i.id);
                    currCategory = "iPhones";
                } else if (string.Equals("androids", category, StringComparison.OrdinalIgnoreCase))
                {
                    phones = _allPhones.Phones.Where(i => i.Category.categoryName.Equals("Android")).OrderBy(i => i.id);
                    currCategory = "Androids";
                } else if (string.Equals("windowsphones", category, StringComparison.OrdinalIgnoreCase))
                {
                    phones = _allPhones.Phones.Where(i => i.Category.categoryName.Equals("WindowsPhone")).OrderBy(i => i.id);
                    currCategory = "WindowsPhones";
                }
            }

            var phoneObj = new PhonesListViewModel
            {
                allPhones = phones,
                currCategory = currCategory
            };
            ViewBag.Title = "Страница с телефонами";

            return View(phoneObj);
        }
            

    }
} 

Shop/Controllers/ShopPhoneController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System.Linq;

namespace Shop.Controllers
{
    public class ShopPhoneController : Controller
    {
        private readonly IAllPhones _phoneRep;
        private readonly ShopPhones _shopPhones;

        public ShopPhoneController(IAllPhones phoneRep, ShopPhones shopPhones)
        {
            _phoneRep = phoneRep;
            _shopPhones = shopPhones; 
        }

        public ViewResult Index()
        {
            var items = _shopPhones.getShopItems();
            _shopPhones.listShopItems = items;

            var obj = new ShopPhoneViewModel
            {
                shopPhones = _shopPhones
            };
            return View(obj);
        }

        public RedirectToActionResult addToPhone(int id)
        {
            var item = _phoneRep.Phones.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopPhones.AddToPhone(item);
            }

            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие телефоны</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Phone phone in Model.favPhones)
        {
            @Html.Partial("AllPhones",phone)
        }
    }
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Order/checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-5">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for ="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ" />
    </form>
</div>

Shop/Views/Phones/List.cshtml
<h1>Все телефоны</h1>
<h3>@Model.currCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Phone phone in Model.allPhones)
        {
            @Html.Partial("AllPhones",phone)
        }
    }
</div>

Shop/Views/Shared/AllPhones.cshtml
@model Phone

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2> @Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopPhone" asp-action="addToPhone" asp-route-id="@Model.id"> Добавить в корзину</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">itProger</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="/">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Phones/List">Смартфоны</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Phones/List/apple">iPhones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Phones/List/androids">Androids</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Phones/List/windowsphones">WindowsPhones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/ShopPhone/">Корзина</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>© 2022 Все права защищены · <a href="#">Соглашение</a></p>
  </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Views/ShopPhone/Index.cshtml
@model ShopPhoneViewModel

<div class="container">
    @foreach (var el in Model.shopPhones.listShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Телефон:</b> @el.phone.name<br />
            <b>Цена:</b> @el.phone.price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>